### ISSUE TITLE
[Feature] Blockvayors

### ISSUE THREAD

**Issue by dmillerw** [GirafiStudios/Impractical-Storage#18]
Feature taken from my old Industrialization mod

Full-size blocks that will move full-size blocks through the world

**Comment by Flabort** [comment]
Personally I get a bit irrationally irritated when mod authors create an issue without providing a description. Usually I don't speak up, but I'm curious is all, what is meant by the title "blockvayors". Something similar to the IE conveyors, but a full block's size? That animate the whole block moving rather than the dropped block item-entity? Those are just guesses, of course, I can't read your mind - no offense meant, just curiosity.

**Comment by dmillerw** [comment]
Does it matter? Issues I post here are for my own reference

**Comment by Flabort** [comment]
No. I was just curious, mostly. And I myself as a person with several projects tend to forget what my own notes mean unless I'm very verbose, so I was thinking a better description than a title would help you too.
But you do what you want. I'm just here to suggest stuff, and if an issue crops up report it. You're the dev, and ultimately in control.

**Comment by dmillerw** [comment]
Implented via 44ad5af747aec56bade95c19fc752a92b318d93a and f03d56ade9398c59ea98bd6327dd1dc2f7fe544c
